// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBkO7uvWxc7yctN3g92cld6g4TZtJ-N8',
    appId: '1:164876643594:android:2da25a04bb5dbe3508def3',
    messagingSenderId: '164876643594',
    projectId: 'datingapp-a8a23',
    storageBucket: 'datingapp-a8a23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUkS2NdQF5_ngPdeOL_BDTJHaR2W8DmFo',
    appId: '1:164876643594:ios:3108966acf83789608def3',
    messagingSenderId: '164876643594',
    projectId: 'datingapp-a8a23',
    storageBucket: 'datingapp-a8a23.appspot.com',
    androidClientId: '164876643594-jkpe3q5k19krmg9nqsl1re6rl4ubbuto.apps.googleusercontent.com',
    iosClientId: '164876643594-5598p4d41r8tj9n39i6bqqksrh8unvnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingapp',
  );

}